### ISSUE TITLE
Set up continuous benchmarking?

### ISSUE THREAD

**Issue by learning-chip** [Algebraic-Programming/ALP#44]
Large effort has been spent on manually benchmarking different algorithms (CG, HPCG, PageRank), Kernels (SpMV, SpMM), backends (blocking/nonblocking), for each commit and version. 

It should be beneficial to set up some continous benchmarking using frameworks like [Google Benchmark](https://github.com/google/benchmark) or [Catch2](https://github.com/catchorg/Catch2/blob/devel/docs/benchmarks.md). It can be further automated [by GitHub Actions](https://github.com/benchmark-action/github-action-benchmark). A nice example is the [Pandas benchmark page](https://pandas.pydata.org/speed/pandas/).

**Comment by learning-chip** [comment]
The [ginkgo](https://github.com/ginkgo-project/ginkgo) linear algebra framework performs continuous benchmarking on GitLab's CI, as described in their [PASC paper](https://dl.acm.org/doi/10.1145/3324989.3325719). The SpMV benchmarks presented in the paper correspond to [this setting](https://github.com/ginkgo-project/ginkgo/blob/396c6c07d3f0f160b14f1f1099ffca21c990e992/.gitlab-ci.yml#L1006)

**Comment by anyzelman** [comment]
There exists the `make perftests` build target since v0.1, which runs extensive performance tests.

Presently, the results of those are written in a machine-readable format to `<build dir>/tests/performance/output/benchmarks`. Internally we do have Jenkins scripts that parses that output and produces performance graphs vs. the commit history. The tests take 1-2 days to complete, however, which is why they're not enabled here.

(Also not enabled are any distributed-memory parallel tests here, will create a new issue for that.)

**Comment by anyzelman** [comment]
Just to update: still looking for inspiration how to best enable perftests externally, aside from on internal resources only. Would be great if the results can auto-publish also.

**Comment by anyzelman** [comment]
Just to update: @byjtew will bring this online for our internal CI. Assigning to him
